import { CreditCard, HotelProgram } from '../data/mockData';
import type { Language } from '../i18n/translations';
import { getMsrDeadlineDate, getMsrDaysRemaining } from './msr';

interface CalendarEvent {
  uid: string;
  title: string;
  description: string;
  startDate: string; // YYYYMMDD or YYYYMMDDTHHMMSSZ
  endDate: string;
  recurrenceRule?: string;
}

function formatDateToICS(d: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}T${pad(d.getHours())}${pad(d.getMinutes())}00Z`;
}

export function generatePerksCalendarICS(
  cards: CreditCard[],
  hotels: HotelProgram[],
  userName: string = 'PointsVault User',
  language: Language = 'en'
): string {
  const events: CalendarEvent[] = [];
  const now = new Date();

  // 1. Monthly Recurring Perk Reminder on the 25th of every month at 10:00 AM
  const monthlyPerks: string[] = [];
  cards.forEach((card) => {
    card.perks.forEach((p) => {
      if (p.frequency === 'Monthly' || p.title.toLowerCase().includes('monthly') || p.title.toLowerCase().includes('uber')) {
        monthlyPerks.push(`• [${card.issuer} ${card.name}] ${p.title} ($${p.value})`);
      }
    });
  });

  if (monthlyPerks.length > 0) {
    const next25th = new Date(now.getFullYear(), now.getMonth(), 25, 10, 0, 0);
    if (now.getDate() > 25) {
      next25th.setMonth(next25th.getMonth() + 1);
    }
    const end25th = new Date(next25th.getTime() + 3600 * 1000); // 1 hour

    events.push({
      uid: `monthly-perks-reminder-${now.getFullYear()}@pointsvault`,
      title:
        language === 'en'
          ? `🔔 PointsVault: Monthly Credit Card Perk Reminder (${monthlyPerks.length} benefits closing soon)`
          : `🔔 PointsVault: 月底信用卡福利打卡提醒 (${monthlyPerks.length} 項福利即將結算)`,
      description:
        language === 'en'
          ? `Only 5 days left in the month. Please check whether the following monthly credits have been claimed:\\n\\n${monthlyPerks.join('\\n')}\\n\\n— Auto-generated by PointsVault`
          : `距離本月底僅剩 5 天，請檢查以下月度報銷是否已完成打卡：\\n\\n${monthlyPerks.join('\\n')}\\n\\n— 由 PointsVault 常旅客資產管理系統自動生成`,
      startDate: formatDateToICS(next25th),
      endDate: formatDateToICS(end25th),
      recurrenceRule: 'RRULE:FREQ=MONTHLY;BYMONTHDAY=25',
    });
  }

  // 2. Semi-Annual Perks (Saks Fifth Avenue, etc.) on June 20 and Dec 20
  const semiAnnualPerks: string[] = [];
  cards.forEach((card) => {
    card.perks.forEach((p) => {
      if (p.title.toLowerCase().includes('saks') || p.title.toLowerCase().includes('semi-annual')) {
        semiAnnualPerks.push(`• [${card.issuer} ${card.name}] ${p.title} ($${p.value})`);
      }
    });
  });

  if (semiAnnualPerks.length > 0) {
    const june20 = new Date(now.getFullYear(), 5, 20, 10, 0, 0);
    const endJune20 = new Date(june20.getTime() + 3600 * 1000);
    events.push({
      uid: `semiannual-june-perks-${now.getFullYear()}@pointsvault`,
      title:
        language === 'en'
          ? `⚠️ PointsVault: H1 Saks / Semi-Annual Card Perks Expiring`
          : `⚠️ PointsVault: 上半年 Saks / 半年度信用卡福利到期警告`,
      description:
        language === 'en'
          ? `H1 benefits reset to zero on June 30! Confirm you've used them:\\n\\n${semiAnnualPerks.join('\\n')}`
          : `6月30日上半年度福利即將清零作廢！請確認使用：\\n\\n${semiAnnualPerks.join('\\n')}`,
      startDate: formatDateToICS(june20),
      endDate: formatDateToICS(endJune20),
      recurrenceRule: 'RRULE:FREQ=YEARLY;BYMONTH=6;BYMONTHDAY=20',
    });

    const dec20 = new Date(now.getFullYear(), 11, 20, 10, 0, 0);
    const endDec20 = new Date(dec20.getTime() + 3600 * 1000);
    events.push({
      uid: `semiannual-dec-perks-${now.getFullYear()}@pointsvault`,
      title:
        language === 'en'
          ? `⚠️ PointsVault: H2 Saks / Semi-Annual Card Perks Expiring`
          : `⚠️ PointsVault: 下半年 Saks / 半年度信用卡福利到期警告`,
      description:
        language === 'en'
          ? `H2 benefits reset to zero on December 31! Confirm you've used them:\\n\\n${semiAnnualPerks.join('\\n')}`
          : `12月31日下半年度福利即將清零作廢！請確認使用：\\n\\n${semiAnnualPerks.join('\\n')}`,
      startDate: formatDateToICS(dec20),
      endDate: formatDateToICS(endDec20),
      recurrenceRule: 'RRULE:FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=20',
    });
  }

  // 3. Hotel Free Night Certificates (FNC) Expiring
  hotels.forEach((hotel) => {
    hotel.fncs.forEach((fnc) => {
      if (!fnc.isUsed && fnc.expirationDate) {
        const expDate = new Date(`${fnc.expirationDate}T10:00:00`);
        const warnDate = new Date(expDate.getTime() - 14 * 24 * 3600 * 1000); // 14 days before
        const endWarn = new Date(warnDate.getTime() + 3600 * 1000);
        const estVal = fnc.estimatedValueUSD ?? (fnc.categoryLimit.includes('85,000') ? 800 : 350);

        events.push({
          uid: `fnc-expiry-${fnc.id}@pointsvault`,
          title:
            language === 'en'
              ? `🏨 PointsVault: ${hotel.name} ${fnc.title} Free Night Expiring (${fnc.expirationDate})`
              : `🏨 PointsVault: ${hotel.name} ${fnc.title} 免房券即將到期 (${fnc.expirationDate})`,
          description:
            language === 'en'
              ? `Your ${hotel.name} ${fnc.title} (${fnc.categoryLimit}) certificate expires in 14 days (${fnc.expirationDate})!\\nEstimated value: $${estVal} USD. Book a stay in time to avoid wasting it.`
              : `您的 ${hotel.name} ${fnc.title} (${fnc.categoryLimit}) 房券將於 14 天後 (${fnc.expirationDate}) 到期！\\n預估價值：$${estVal} USD。請及時鎖定酒店房間避免浪費。`,
          startDate: formatDateToICS(warnDate),
          endDate: formatDateToICS(endWarn),
        });
      }
    });
  });

  // 4. MSR Spend Deadlines
  cards.forEach((card) => {
    if (card.msr && card.msr.currentSpend < card.msr.requiredSpend && getMsrDaysRemaining(card) > 0) {
      const msrExp = getMsrDeadlineDate(card);
      const warnDate = new Date(msrExp.getTime() - 7 * 24 * 3600 * 1000);
      const endWarn = new Date(warnDate.getTime() + 3600 * 1000);

      events.push({
        uid: `msr-deadline-${card.id}@pointsvault`,
        title:
          language === 'en'
            ? `💳 PointsVault: ${card.name} MSR Deadline Final Countdown`
            : `💳 PointsVault: ${card.name} 開卡 MSR 截止最後倒計時`,
        description:
          language === 'en'
            ? `Spend $${(card.msr.requiredSpend - card.msr.currentSpend).toLocaleString()} more to unlock ${card.msr.bonusPoints.toLocaleString()} bonus points!\\nComplete your spend within 7 days so the bonus isn't forfeited.`
            : `尚差 $${(card.msr.requiredSpend - card.msr.currentSpend).toLocaleString()} 即可解鎖 ${card.msr.bonusPoints.toLocaleString()} 開卡獎勵點數！\\n請於 7 天內完成消費以防獎勵失效。`,
        startDate: formatDateToICS(warnDate),
        endDate: formatDateToICS(endWarn),
      });
    }
  });

  // Build iCalendar string
  const icsLines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//PointsVault//Credit Card Perks & FNC Calendar//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${language === 'en' ? `PointsVault Perks & Benefits Calendar (${userName})` : `PointsVault 玩卡與福利日曆 (${userName})`}`,
    'X-WR-TIMEZONE:America/New_York',
  ];

  events.forEach((evt) => {
    icsLines.push('BEGIN:VEVENT');
    icsLines.push(`UID:${evt.uid}`);
    icsLines.push(`DTSTAMP:${formatDateToICS(now)}`);
    icsLines.push(`DTSTART:${evt.startDate}`);
    icsLines.push(`DTEND:${evt.endDate}`);
    icsLines.push(`SUMMARY:${evt.title}`);
    icsLines.push(`DESCRIPTION:${evt.description}`);
    if (evt.recurrenceRule) {
      icsLines.push(evt.recurrenceRule);
    }
    icsLines.push('STATUS:CONFIRMED');
    icsLines.push('TRANSP:TRANSPARENT');
    icsLines.push('END:VEVENT');
  });

  icsLines.push('END:VCALENDAR');

  return icsLines.join('\r\n');
}

export function downloadCalendarICS(icsContent: string, fileName: string = 'pointsvault_perks.ics') {
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', fileName);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
