import React, { useState } from 'react';
import {
  X,
  Smartphone,
  Copy,
  Check,
  Sparkles,
  ShoppingBag,
  Utensils,
  Fuel,
  Plane,
  CreditCard as CardIcon,
} from 'lucide-react';
import { useAppStore } from '../store/useAppStore';
import { t } from '../i18n/translations';

interface P2CheatSheetModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const P2CheatSheetModal: React.FC<P2CheatSheetModalProps> = ({ isOpen, onClose }) => {
  const language = useAppStore((s) => s.language);
  const cards = useAppStore((s) => s.cards);
  const profile = useAppStore((s) => s.profile);
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  // Filter P2 cards (or all cards if P2 has fewer than 2)
  const p2Cards = cards.filter((c) => c.player === 'P2');
  const poolCards = p2Cards.length >= 2 ? p2Cards : cards;

  // Find best card for key categories
  const getBestCard = (categoryName: string, fallbackName: string) => {
    let best = poolCards[0];
    let maxMult = 1;

    poolCards.forEach((card) => {
      card.multipliers.forEach((m) => {
        if (m.category.toLowerCase().includes(categoryName.toLowerCase()) && m.rate > maxMult) {
          maxMult = m.rate;
          best = card;
        }
      });
    });

    return {
      card: best,
      multiplier: maxMult > 1 ? `${maxMult}x` : '2x/1.5x',
      fallback: fallbackName,
    };
  };

  const grocery = getBestCard('grocery', 'Amex Gold / CFF');
  const dining = getBestCard('dining', 'Amex Gold / CSP');
  const gas = getBestCard('gas', 'Citi Custom Cash / CFF');
  const travel = getBestCard('travel', 'Venture X / CSP');
  const general = getBestCard('everything', 'Venture X / CFU');

  const cheatSheetText =
    language === 'en'
      ? `💳 【${profile.p2Name}'s Personal Card Cheat Sheet】
🛒 Groceries: ${grocery.card?.name || 'Amex Gold'} (${grocery.multiplier})
🍽️ Dining: ${dining.card?.name || 'Amex Gold'} (${dining.multiplier})
⛽ Gas / EV Charging: ${gas.card?.name || 'Citi Custom Cash'} (${gas.multiplier})
✈️ Flights / Travel: ${travel.card?.name || 'Venture X'} (${travel.multiplier})
📦 Everything Else / Costco: ${general.card?.name || 'Venture X (2x)'}
— Auto-generated by PointsVault`
      : `💳 【${profile.p2Name} 專屬刷卡指南便簽】
🛒 超市買菜: ${grocery.card?.name || 'Amex Gold'} (${grocery.multiplier})
🍽️ 餐廳聚餐: ${dining.card?.name || 'Amex Gold'} (${dining.multiplier})
⛽ 加油/充電: ${gas.card?.name || 'Citi Custom Cash'} (${gas.multiplier})
✈️ 機票/旅行: ${travel.card?.name || 'Venture X'} (${travel.multiplier})
📦 其他任意刷/Costco: ${general.card?.name || 'Venture X (2x)'}
— 由 PointsVault 自動生成`;

  const handleCopy = () => {
    navigator.clipboard.writeText(cheatSheetText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-fadeIn">
      <div className="glass-panel w-full max-w-lg rounded-3xl border border-slate-800 p-6 space-y-5 bg-slate-950 shadow-2xl relative">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center space-x-2">
            <span className="p-2 bg-indigo-500/10 border border-indigo-500/30 rounded-xl text-indigo-400">
              <Smartphone className="w-5 h-5" />
            </span>
            <div>
              <h3 className="text-base font-black text-white">
                {language === 'en' ? `${profile.p2Name}'s Wallet Cheat Sheet` : `📱 ${profile.p2Name} 專屬刷卡指南便簽`}
              </h3>
              <p className="text-[11px] text-slate-400">
                {language === 'en' ? 'One-click copy or save as lockscreen reminder for your partner' : '一鍵複製或截圖發給 P2 伴侶，結賬不再糾結刷哪張卡'}
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Visual Phone Card Preview */}
        <div className="p-5 rounded-3xl bg-gradient-to-b from-slate-900 via-indigo-950/40 to-slate-950 border border-indigo-500/30 shadow-2xl space-y-3.5 relative overflow-hidden">
          <div className="flex items-center justify-between border-b border-white/10 pb-2.5">
            <span className="text-xs font-black text-indigo-300 flex items-center space-x-1.5">
              <Sparkles className="w-4 h-4 text-amber-400" />
              {language === 'en' ? (
                <span>{profile.p2Name}'s Card Decision Cheat Sheet</span>
              ) : (
                <span>{profile.p2Name} 的刷卡決策便簽</span>
              )}
            </span>
            <span className="text-[10px] text-slate-400 font-bold bg-black/40 px-2 py-0.5 rounded-full border border-white/10">
              PointsVault
            </span>
          </div>

          <div className="space-y-2 text-xs">
            <div className="flex items-center justify-between p-2.5 bg-slate-950/80 rounded-xl border border-slate-800">
              <span className="flex items-center space-x-2 text-slate-300 font-bold">
                <ShoppingBag className="w-4 h-4 text-emerald-400" />
                {language === 'en' ? <span>🛒 Groceries</span> : <span>🛒 超市買菜 (Groceries)</span>}
              </span>
              <span className="font-extrabold text-amber-300">{grocery.card?.name || 'Amex Gold'} ({grocery.multiplier})</span>
            </div>

            <div className="flex items-center justify-between p-2.5 bg-slate-950/80 rounded-xl border border-slate-800">
              <span className="flex items-center space-x-2 text-slate-300 font-bold">
                <Utensils className="w-4 h-4 text-amber-400" />
                {language === 'en' ? <span>🍽️ Dining</span> : <span>🍽️ 餐廳聚餐 (Dining)</span>}
              </span>
              <span className="font-extrabold text-amber-300">{dining.card?.name || 'Amex Gold'} ({dining.multiplier})</span>
            </div>

            <div className="flex items-center justify-between p-2.5 bg-slate-950/80 rounded-xl border border-slate-800">
              <span className="flex items-center space-x-2 text-slate-300 font-bold">
                <Fuel className="w-4 h-4 text-rose-400" />
                {language === 'en' ? <span>⛽ Gas / EV Charging</span> : <span>⛽ 加油/充電 (Gas)</span>}
              </span>
              <span className="font-extrabold text-rose-300">{gas.card?.name || 'Citi Custom Cash'} ({gas.multiplier})</span>
            </div>

            <div className="flex items-center justify-between p-2.5 bg-slate-950/80 rounded-xl border border-slate-800">
              <span className="flex items-center space-x-2 text-slate-300 font-bold">
                <Plane className="w-4 h-4 text-sky-400" />
                {language === 'en' ? <span>✈️ Flights / Travel</span> : <span>✈️ 機票/旅行 (Travel)</span>}
              </span>
              <span className="font-extrabold text-sky-300">{travel.card?.name || 'Venture X'} ({travel.multiplier})</span>
            </div>

            <div className="flex items-center justify-between p-2.5 bg-slate-950/80 rounded-xl border border-indigo-500/30">
              <span className="flex items-center space-x-2 text-slate-300 font-bold">
                <CardIcon className="w-4 h-4 text-indigo-400" />
                {language === 'en' ? <span>📦 Everything Else / Costco</span> : <span>📦 其他任意刷 / Costco</span>}
              </span>
              <span className="font-extrabold text-indigo-300">{general.card?.name || 'Venture X (2x / 1.5x)'}</span>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center justify-end space-x-3 pt-2">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-slate-800 text-slate-300 text-xs font-semibold hover:bg-slate-700 transition-colors"
          >
            {t(language, 'cancel')}
          </button>

          <button
            onClick={handleCopy}
            className="px-5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold shadow-lg shadow-indigo-500/30 flex items-center space-x-1.5 transition-all active:scale-95"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-emerald-400" />
                <span>{language === 'en' ? 'Copied to Clipboard!' : '已複製便簽文字！'}</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                <span>{language === 'en' ? 'Copy Text Message' : '複製到剪貼簿 / 發送給 P2'}</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
